### ISSUE TITLE
Linux issues

### ISSUE THREAD

**Issue by orionblastar** [orionblastar/K666#36]
I think using Linux MInt might have been a mistake. I tried installing Tensorflow and got this error

tensorflow-0.12.0rc0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

Linux Mint is supposed to be easier to use and configure that Ubuntu and Debian and others. It does not support every wheel and library. Which might be why VirtualBox died on me and I can't seem to get Docker to work correctly.

I'm thinking of going back to Lubuntu as Ubuntu has that Unity crap, and Debian only has older packages because they want to stay stable.

**Comment by procrasti** [comment]
Okay... you don't actually need docker to work on freek666... if you can get that working it will be a bonus, but all you need is virtualenv. Tensorflow might not be available on your machine for many reasons that will not affect freek666... because tensorflow probably also depends on your GPU and other things?
